### ISSUE TITLE
no attribute 'ForProtocol'

### ISSUE THREAD

**Issue by flav1972** [ronreiter/webmux#1]
Hi,

I'm getting following error. Any clue ?
Thanks, 
Flav

2015-04-11 08:02:36+0200 [-] Log opened.
2015-04-11 08:02:36+0200 [-] Traceback (most recent call last):
2015-04-11 08:02:36+0200 [-]   File "/usr/local/bin/webmuxd", line 5, in <module>
2015-04-11 08:02:36+0200 [-]     pkg_resources.run_script('webmux==0.1.11', 'webmuxd')
2015-04-11 08:02:36+0200 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
2015-04-11 08:02:36+0200 [-]     self.require(requires)[0].run_script(script_name, ns)
2015-04-11 08:02:36+0200 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
2015-04-11 08:02:36+0200 [-]     execfile(script_filename, namespace, namespace)
2015-04-11 08:02:36+0200 [-]   File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/EGG-INFO/scripts/webmuxd", line 3, in <module>
2015-04-11 08:02:36+0200 [-]     from webmux.main import main
2015-04-11 08:02:36+0200 [-]   File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/webmux/main.py", line 11, in <module>
2015-04-11 08:02:36+0200 [-]     from webmux.protocols import TerminalFactory
2015-04-11 08:02:36+0200 [-]   File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/webmux/protocols.py", line 61, in <module>
2015-04-11 08:02:36+0200 [-]     TerminalFactory = SockJSPubSubFactory.forProtocol(TerminalProtocol)
2015-04-11 08:02:36+0200 [-] AttributeError: class SockJSPubSubFactory has no attribute 'forProtocol'

**Comment by ronreiter** [comment]
Looks like a version issue. Not sure what to do but you should try updating
SockJS and Twisted.

- Ron


[image: Facebook] <http://www.facebook.com/ron.reiter> [image: Twitter]
<http://twitter.com/#!/ronreiter> [image: LinkedIn]
<http://www.linkedin.com/profile/view?id=4436607&locale=en_US&trk=tab_pro>

**Comment by flav1972** [comment]
Hi Ron,

Thanks,
Your right. There were some dependencies issues. I didn't found exactly which one it was broken as I have upgraded a lot of stuff.

Regards,
Flav
