### ISSUE TITLE
No module named txsockjs.factory

### ISSUE THREAD

**Issue by maikeldus** [ronreiter/webmux#2]
When i follow http://ronreiter.github.io/webmux/ all goes well until I want to start the `webmuxd`. It states:

```
Traceback (most recent call last):
  File "/usr/local/bin/webmuxd", line 5, in <module>
    pkg_resources.run_script('webmux==0.1.11', 'webmuxd')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/EGG-INFO/scripts/webmuxd", line 3, in <module>
    from webmux.main import main
  File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/webmux/main.py", line 6, in <module>
    from txsockjs.factory import SockJSResource
ImportError: No module named txsockjs.factory
```

I ran ` sudo pip install txsockjs sqlobject jinja2` but now I get:

```
2015-08-30 22:06:47+0200 [-] Log opened.
2015-08-30 22:06:48+0200 [-] Traceback (most recent call last):
2015-08-30 22:06:48+0200 [-]   File "/usr/local/bin/webmuxd", line 5, in <module>
2015-08-30 22:06:48+0200 [-]     pkg_resources.run_script('webmux==0.1.11', 'webmuxd')
2015-08-30 22:06:48+0200 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
2015-08-30 22:06:48+0200 [-]     self.require(requires)[0].run_script(script_name, ns)
2015-08-30 22:06:48+0200 [-]   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
2015-08-30 22:06:48+0200 [-]     execfile(script_filename, namespace, namespace)
2015-08-30 22:06:48+0200 [-]   File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/EGG-INFO/scripts/webmuxd", line 3, in <module>
2015-08-30 22:06:48+0200 [-]     from webmux.main import main
2015-08-30 22:06:48+0200 [-]   File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/webmux/main.py", line 11, in <module>
2015-08-30 22:06:48+0200 [-]     from webmux.protocols import TerminalFactory
2015-08-30 22:06:48+0200 [-]   File "/usr/local/lib/python2.7/dist-packages/webmux-0.1.11-py2.7.egg/webmux/protocols.py", line 61, in <module>
2015-08-30 22:06:48+0200 [-]     TerminalFactory = SockJSPubSubFactory.forProtocol(TerminalProtocol)
2015-08-30 22:06:48+0200 [-] AttributeError: class SockJSPubSubFactory has no attribute 'forProtocol'

```

Using Raspbian.

**Comment by ronreiter** [comment]
Try running pipe install -r requirements.txt, it has an accurate list of requirements.

**Comment by SudoHenk** [comment]
Thx

**Comment by maikeldus** [comment]
Oh derp, forgot that ...
